# настройки для NGINX

server {
    listen 80;
    server_name _;

    root /var/www/diplom;
    index index.html;

    # SPA: все пути в index.html
    location / {
        try_files $uri $uri/ /index.html;
    }

    # API в бэкенд
    location /api/ {
        proxy_pass http://localhost:8000/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # Статика (постеры, QR) в бэкенд
    location /static/ {
        proxy_pass http://localhost:8000/static/;
        proxy_set_header Host $host;
    }
}