services:
  db: # сервис № 1 - База данных PostgreSQL
    image: postgres:18-alpine
    env_file:
      - backend/app/.env
    environment:
      POSTGRES_INITDB_ARGS: "--locale=C --encoding=UTF8"
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U mySuperUser -d cinema"]
      interval: 5s
      timeout: 5s
      retries: 5

  web: # сервис № 2 - приложение
    build: .
    env_file:
      - backend/app/.env
    environment:
      DB_HOST: db
      DB_PORT: 5432
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy

volumes:
  pgdata: